<?php

namespace Owbaz\SiteBundle\Repository;

/**
 * IndustriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndustriesRepository extends \Doctrine\ORM\EntityRepository
{
}
