<?php

namespace Owbaz\SiteBundle\Repository;

/**
 * IndustryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndustryTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
