<?php

namespace Owbaz\SiteBundle\Repository;

/**
 * JobsCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobsCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
