owbaz_jobs:
    resource: "@OwbazJobsBundle/Resources/config/routing.yml"
    prefix:   /

owbaz_employer:
    resource: "@OwbazEmployerBundle/Resources/config/routing.yml"
    prefix:   /

owbaz_jobseeker:
    resource: "@OwbazJobseekerBundle/Resources/config/routing.yml"
    prefix:   /

owbaz_user:
    resource: "@OwbazUserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
