owbaz_user_jobseeker_new:
    pattern:  /jobseeker/new
    defaults: { _controller: OwbazUserBundle:User:newJobseeker }

users_jobseekers_create:
    pattern:  /users/jobseeker/create
    defaults: { _controller: OwbazUserBundle:User:createJobseeker }

owbaz_jobseeker_dashboard:
    pattern:  jobseeker/dashboard
    defaults: { _controller: OwbazUserBundle:User:jobseekerdashboard }