<?php

namespace Owbaz\JobsBundle\Repository;

/**
 * JobsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllJobs()
    {
       $total_record = $this->getEntityManager()
                ->createQuery('SELECT j FROM OwbazJobsBundle:Jobs j');
        try {
            return $total_record->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
