<?php

namespace Owbaz\UserBundle\Repository;

/**
 * UserDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
