<?php

namespace Owbaz\UserBundle\Repository;
use Doctrine\ORM\Mapping as ORM;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function userLogin($email,$password)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT s FROM OwbazUserBundle:User s
     WHERE
     s.email=:email
     AND s.password=:password"
            )->setParameters(array('email' => $email, 'password' =>$password));
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
