<?php

namespace Owbaz\UserBundle\Repository;
use Doctrine\ORM\Mapping as ORM;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function userLogin($email,$password)
    {
        $query = $this->getEntityManager()
            ->createQuery("
            SELECT u FROM OwbazUserBundle:User u
            WHERE u.email = :email AND u.password= :password"
            )->setParameters(array('email' => $email, 'password' =>$password));

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
