<?php

namespace Owbaz\JobseekerBundle\Repository;

/**
 * JobPreferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobPreferencesRepository extends \Doctrine\ORM\EntityRepository
{
}
