<?php

namespace Owbaz\JobseekerBundle\Repository;

/**
 * JobseekersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobseekersRepository extends \Doctrine\ORM\EntityRepository
{
}
