owbaz_employeer_routes:
    resource: "@OwbazUserBundle/Resources/config/routing/employees.yml"
    prefix:   /
    
owbaz_jobseeker_routes:
    resource: "@OwbazUserBundle/Resources/config/routing/jobseekers.yml"
    prefix:   /

owbaz_users_login:
    pattern:  /owbaz/user/login
    defaults: { _controller: OwbazUserBundle:User:userLogin }

owbaz_users_login_check:
    pattern:  /owbaz/user/checklogin
    defaults: { _controller: OwbazUserBundle:User:checkUserLogin }

#---------------------------------------------- Login ------------------------------------------

admin_login:
    pattern:   /admin/login
    defaults:  { _controller: OwbazUserBundle:Security:adminLogin }

admin:
    pattern:   /admin
    defaults:  { _controller: OwbazUserBundle:Security:adminLogin }

login:
    pattern:   /login
    defaults: { _controller: OwbazUserBundle:Security:login }
    #defaults:  { _controller: OwbazUserBundle:Security:login }

login_check:
    pattern:   /login_check

admin_logout:
    pattern:   /logout
    
logout:
    pattern:   /logout    