owbaz_employeer_routes:
    resource: "@OwbazUserBundle/Resources/config/routing/employees.yml"
    prefix:   /
    
owbaz_jobseeker_routes:
    resource: "@OwbazUserBundle/Resources/config/routing/jobseekers.yml"
    prefix:   /

owbaz_users_login:
    pattern:  /owbaz/user/login
    defaults: { _controller: OwbazUserBundle:User:userLogin }

owbaz_users_login_check:
    pattern:  /owbaz/user/checklogin
    defaults: { _controller: OwbazUserBundle:User:checkUserLogin }